name: Java CI

# Run the CI on push and pull requests again master.
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Set up the environment.
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      # Build the program and run the tests.
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      # Store the generated artifacts for review.
      - name: Packaging build artifacts
        run: mkdir staging && cp target/*.jar staging
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
